name: 02 - Eventos
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '00 18 2 3 *'

jobs:
  saludo: 
    runs-on: ubuntu-latest
    steps:

      - name: ShowTrigger
        run: |
          echo "Event name: ${{ github.event_name }}"
